///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VSTSforDaBoys
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VSTSforDaBoysRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("68ec5fa0-c6f8-44b5-a452-d1062a1dc161")]
    public partial class VSTSforDaBoysRepository : RepoGenBaseFolder
    {
        static VSTSforDaBoysRepository instance = new VSTSforDaBoysRepository();
        VSTSforDaBoysRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder _ranorexvipdatabasetestwebapplicatio;

        /// <summary>
        /// Gets the singleton class instance representing the VSTSforDaBoysRepository element repository.
        /// </summary>
        [RepositoryFolder("68ec5fa0-c6f8-44b5-a452-d1062a1dc161")]
        public static VSTSforDaBoysRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VSTSforDaBoysRepository() 
            : base("VSTSforDaBoysRepository", "/", null, 0, false, "68ec5fa0-c6f8-44b5-a452-d1062a1dc161", ".\\RepositoryImages\\VSTSforDaBoysRepository68ec5fa0.rximgres")
        {
            _ranorexvipdatabasetestwebapplicatio = new VSTSforDaBoysRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("68ec5fa0-c6f8-44b5-a452-d1062a1dc161")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatio folder.
        /// </summary>
        [RepositoryFolder("acf5878e-f2cc-4cf8-ae2c-ce913586db16")]
        public virtual VSTSforDaBoysRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder RanorexVIPDatabaseTestWebApplicatio
        {
            get { return _ranorexvipdatabasetestwebapplicatio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class VSTSforDaBoysRepositoryFolders
    {
        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatioAppFolder folder.
        /// </summary>
        [RepositoryFolder("acf5878e-f2cc-4cf8-ae2c-ce913586db16")]
        public partial class RanorexVIPDatabaseTestWebApplicatioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _somebodytagInfo;

            /// <summary>
            /// Creates a new RanorexVIPDatabaseTestWebApplicatio  folder.
            /// </summary>
            public RanorexVIPDatabaseTestWebApplicatioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexVIPDatabaseTestWebApplicatio", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "acf5878e-f2cc-4cf8-ae2c-ce913586db16", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", 30000, null, "6080bfbd-f3a7-4271-a375-bb319586a289");
                _somebodytagInfo = new RepoItemInfo(this, "SomeBodyTag", "body", 30000, null, "6eab03bd-efd6-48eb-8693-45658ba6ab8e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("acf5878e-f2cc-4cf8-ae2c-ce913586db16")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("acf5878e-f2cc-4cf8-ae2c-ce913586db16")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("6080bfbd-f3a7-4271-a375-bb319586a289")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("6080bfbd-f3a7-4271-a375-bb319586a289")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The SomeBodyTag item.
            /// </summary>
            [RepositoryItem("6eab03bd-efd6-48eb-8693-45658ba6ab8e")]
            public virtual Ranorex.BodyTag SomeBodyTag
            {
                get
                {
                    return _somebodytagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The SomeBodyTag item info.
            /// </summary>
            [RepositoryItemInfo("6eab03bd-efd6-48eb-8693-45658ba6ab8e")]
            public virtual RepoItemInfo SomeBodyTagInfo
            {
                get
                {
                    return _somebodytagInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}